name: Build & Publish Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  REGISTRY: ${{ secrets.ACR_REGISTRY }}
  NAMESPACE: ${{ secrets.ACR_NAMESPACE }}
  REPOSITORY: ${{ secrets.ACR_REPOSITORY }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Validate image coordinates
        run: |
          [ -n "$NAMESPACE" ] || { echo "Missing secrets.ACR_NAMESPACE"; exit 1; }
          [ -n "$REPOSITORY" ] || { echo "Missing secrets.ACR_REPOSITORY"; exit 1; }

      - name: Log in to Alibaba Cloud Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.NAMESPACE }}/${{ env.REPOSITORY }}
          tags: |
            type=ref,event=branch
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}


